### ISSUE TITLE
Make SPTypeEnumeration an Enum Class

### ISSUE THREAD

**Issue by bennypi** [litsec/eidas-opensaml#36]
SPTypeEnumeration ist a final class with two public static final instances of itself, PUBLIC and PRIVATE.
It contains most of a typical Enum class, but is missing the valueOf(...) method.
As this class contains no functionality to create an object from a String representation of public or private, it is quite a hassle to determine if an arbitrary String is equal to the value of PRIVATE or PUBLIC.

My suggestion would be to make this a public enum class or add a valueOf(...) method to this class. If this suggestion is approved, I'm happy to provide a pull request.

**Comment by martin-lindstrom** [comment]
I don't remember why we didn't go for the obvious choice of using an enum here. I probably looked at how OpenSAML handles enum-like values in other places.

I'll look into it and see if I can convert it into an enum without introducing any backwards incompatible problems for users. Otherwise, I'll add a valueOf() method to the class.

**Comment by martin-lindstrom** [comment]
Fixed in PR https://github.com/litsec/eidas-opensaml/pull/37. 

Will be included in the forthcoming 1.4.4 release.
